name: Trigger auto deployment for portfolio

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'Jayesh-portfolio/**'
    - '.github/workflows/portfolio-AutoDeployTrigger-80cea0d0-5ead-4e0c-ac0a-d19a4815149e.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: jayesh.azurecr.io
          username: ${{ secrets.PORTFOLIO_REGISTRY_USERNAME }}
          password: ${{ secrets.PORTFOLIO_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: jayesh.azurecr.io/portfolio:${{ github.sha }}
          file: Jayesh-portfolio/Dockerfile
          context: Jayesh-portfolio/


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.PORTFOLIO_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n portfolio -g DefaultResourceGroup-EUS2 --server jayesh.azurecr.io --username  ${{ secrets.PORTFOLIO_REGISTRY_USERNAME }} --password ${{ secrets.PORTFOLIO_REGISTRY_PASSWORD }}
            az containerapp update -n portfolio -g DefaultResourceGroup-EUS2 --image jayesh.azurecr.io/portfolio:${{ github.sha }}
